const rowData = [
  {
    area_name: "Mira-Bhayandar",
    total_cases: 9,
    total_active: 4,
    total_recovered: 4,
    total_deaths: 1,
  },
  {
    area_name: "Dongri",
    total_cases: 4,
    total_active: 0,
    total_recovered: 3,
    total_deaths: 1,
  },
  {
    area_name: "Bandra",
    total_cases: 1,
    total_active: 1,
    total_recovered: 0,
    total_deaths: 0,
  },
  {
    area_name: "Andheri",
    total_cases: 1,
    total_active: 1,
    total_recovered: 0,
    total_deaths: 0,
  },
  {
    area_name: "Govandi",
    total_cases: 1,
    total_active: 1,
    total_recovered: 0,
    total_deaths: 0,
  },
  {
    area_name: "Pune",
    total_cases: 3,
    total_active: 3,
    total_recovered: 0,
    total_deaths: 0,
  },
  {
    area_name: "Sangli",
    total_cases: 0,
    total_active: 0,
    total_recovered: 0,
    total_deaths: 0,
  },
  {
    area_name: "Wadala",
    total_cases: 1,
    total_active: 1,
    total_recovered: 0,
    total_deaths: 0,
  },
  {
    area_name: "Kurla",
    total_cases: 2,
    total_active: 1,
    total_recovered: 1,
    total_deaths: 0,
  },
  {
    area_name: "Mumbra",
    total_cases: 1,
    total_active: 1,
    total_recovered: 0,
    total_deaths: 0,
  },
  // {
  //   area_name: "",
  //   total_cases: 0,
  //   total_active: 0,
  //   total_recovered: 0,
  //   total_deaths: 0,
  // },
];

export default rowData;
